import { promises as fs } from 'fs';
import path from 'path';
import { stringify } from 'yaml';
import { discoverBundleCandidates } from './candidates.js';
import { createBundleDraft, optimizeBundleDraft } from './draft.js';
import { composeBundleFactoryPlan } from './factory-compose.js';
import {
  normalizeBundleFactoryPlan,
  readBundleFactoryPlan,
  writeBundleFactoryPlanArtifact,
} from './factory-plan.js';
import { readSkillPreferences } from './preferences.js';
import { reconcileBundleAuthoringState, writeBundleAuthoringState } from './state.js';
import { generateFactorySkillPackage } from '../factory/package.js';
import { hashBundle } from './hash.js';
import { loadBundle } from './load.js';
import type { BundleAuthoringState, BundleFactoryMetadata, BundleManifest } from './types.js';

function slug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/gu, '-')
    .replace(/^-+|-+$/gu, '');
}

function entrySkillId(state: BundleAuthoringState): string {
  return slug(state.name);
}

function isMissingStateError(error: unknown): boolean {
  return (
    error instanceof Error && 'code' in error && (error as NodeJS.ErrnoException).code === 'ENOENT'
  );
}

function bundleManifest(state: BundleAuthoringState, skillId: string): BundleManifest {
  return {
    apiVersion: 'comet/v1alpha1',
    kind: 'SkillBundle',
    metadata: {
      name: state.name,
      version: state.base?.version ?? '1.0.0',
      description: state.factory?.goal ?? `Generated Comet Skill Factory bundle for ${state.name}.`,
      defaultLocale: state.defaultLocale,
      locales: [...state.locales],
    },
    skills: [
      {
        id: skillId,
        path: `skills/${skillId}`,
        visibility: 'entry',
      },
    ],
    resources: {
      rules: [
        {
          id: `${skillId}-orchestration`,
          path: `rules/${skillId}-orchestration.md`,
          mode: 'always',
          required: true,
        },
      ],
      hooks: [
        {
          id: `${skillId}-before-write-guard`,
          path: `hooks/${skillId}-before-write-guard.yaml`,
        },
        {
          id: `${skillId}-before-tool-guard`,
          path: `hooks/${skillId}-before-tool-guard.yaml`,
        },
      ],
      references: [
        `skills/${skillId}/reference/resolved-skills.json`,
        `skills/${skillId}/reference/composition-report.md`,
      ],
      scripts: [
        {
          id: 'comet-plan',
          path: `skills/${skillId}/scripts/comet-plan.mjs`,
          sideEffect: 'write',
          runtime: 'node',
        },
        {
          id: 'comet-check',
          path: `skills/${skillId}/scripts/comet-check.mjs`,
          sideEffect: 'read',
          runtime: 'node',
        },
        {
          id: 'comet-hook-guard',
          path: `skills/${skillId}/scripts/comet-hook-guard.mjs`,
          sideEffect: 'read',
          runtime: 'node',
        },
      ],
      assets: [],
    },
    platforms: {
      requires: ['skills', 'scripts', 'rules', 'hooks', 'references'],
      optional: [],
      overrides: [],
    },
    // Bundle-level engine packaging is a separate legacy channel. Factory output
    // currently embeds Comet-native runtime files inside the generated entry Skill.
    engine: { enabled: false },
  };
}

function orchestrationRule(skillId: string): string {
  return `# ${skillId} Orchestration

This Bundle is generated by the Comet Skill Factory and uses a portable control plane.

- Entry Skill: \`skills/${skillId}/SKILL.md\`
- Plan script: \`skills/${skillId}/scripts/comet-plan.mjs\`
- Check script: \`skills/${skillId}/scripts/comet-check.mjs\`
- Hook guard script: \`skills/${skillId}/scripts/comet-hook-guard.mjs\`

Run the generated Skill through its declared call chain and keep resolved Skill evidence in \`skills/${skillId}/reference/\`.
`;
}

function hookDescriptor(event: 'before_write' | 'before_tool'): string {
  const matcher = event === 'before_write' ? 'Write|Edit' : '"*"';
  return `event: ${event}
matcher: ${matcher}
script: comet-hook-guard
failure: block
requiresConfirmation: false
`;
}

function beforeWriteHookDescriptor(): string {
  return hookDescriptor('before_write');
}

function beforeToolHookDescriptor(): string {
  return hookDescriptor('before_tool');
}

async function clearDirectory(root: string): Promise<void> {
  await fs.mkdir(root, { recursive: true });
  const entries = await fs.readdir(root, { withFileTypes: true });
  await Promise.all(
    entries.map((entry) =>
      fs.rm(path.join(root, entry.name), {
        recursive: true,
        force: true,
      }),
    ),
  );
}

function assertFactoryCandidatesResolved(state: BundleAuthoringState): void {
  const unresolved = state.factory?.resolvedSkills.filter(
    (skill) => skill.status === 'missing' || skill.status === 'ambiguous',
  );
  if (!unresolved || unresolved.length === 0) return;
  throw new Error(
    `Bundle ${state.name} has unresolved factory Skill candidates: ${unresolved
      .map((skill) => `${skill.query} (${skill.status})`)
      .join(', ')}`,
  );
}

function assertFactoryCompositionReady(name: string, factory: BundleFactoryMetadata): void {
  const issues = factory.composition?.issues ?? [];
  if (issues.length === 0) return;
  throw new Error(
    `Bundle ${name} has unresolved factory composition issues: ${issues
      .map((issue) => issue.message)
      .join('; ')}`,
  );
}

export async function composeFactoryMetadata(
  factory: BundleFactoryMetadata,
): Promise<BundleFactoryMetadata> {
  const compositionEntrySkills =
    factory.compositionEntrySkills && factory.compositionEntrySkills.length > 0
      ? factory.compositionEntrySkills
      : factory.callChain.map((item) => item.skill);
  const composed = await composeBundleFactoryPlan({
    entrySkills: compositionEntrySkills,
    preferredSkills: factory.preferredSkills,
    resolvedSkills: factory.resolvedSkills,
  });
  return {
    ...factory,
    compositionEntrySkills: [...compositionEntrySkills],
    callChain: composed.callChain.length > 0 ? composed.callChain : factory.callChain,
    composition: composed.composition,
  };
}

export async function generateBundleDraftFromFactoryState(options: {
  projectRoot: string;
  state: BundleAuthoringState;
}): Promise<BundleAuthoringState> {
  const { state } = options;
  if (!state.factory) {
    throw new Error(`Bundle ${state.name} does not have factory metadata`);
  }
  assertFactoryCandidatesResolved(state);
  const factory = state.factory.composition
    ? state.factory
    : await composeFactoryMetadata(state.factory);
  assertFactoryCompositionReady(state.name, factory);

  const skillId = entrySkillId(state);
  await clearDirectory(state.draftPath);
  await fs.writeFile(
    path.join(state.draftPath, 'bundle.yaml'),
    stringify(bundleManifest(state, skillId)),
    'utf8',
  );

  const generated = await generateFactorySkillPackage({
    root: state.draftPath,
    name: skillId,
    version: state.base?.version ?? '1.0.0',
    description: factory.goal,
    goal: factory.goal,
    defaultLocale: state.defaultLocale,
    callChain: factory.callChain,
    composition: factory.composition,
    resolvedSkills: factory.resolvedSkills,
    deviations: factory.deviations,
    engineMode: factory.engineMode,
  });
  await fs.mkdir(path.join(state.draftPath, 'rules'), { recursive: true });
  await fs.writeFile(
    path.join(state.draftPath, 'rules', `${skillId}-orchestration.md`),
    orchestrationRule(skillId),
    'utf8',
  );
  await fs.mkdir(path.join(state.draftPath, 'hooks'), { recursive: true });
  await fs.writeFile(
    path.join(state.draftPath, 'hooks', `${skillId}-before-write-guard.yaml`),
    beforeWriteHookDescriptor(),
    'utf8',
  );
  await fs.writeFile(
    path.join(state.draftPath, 'hooks', `${skillId}-before-tool-guard.yaml`),
    beforeToolHookDescriptor(),
    'utf8',
  );

  const bundle = await loadBundle(state.draftPath);
  const currentHash = await hashBundle(bundle);
  const updated: BundleAuthoringState = {
    ...state,
    status: 'draft',
    currentHash,
    factory: {
      ...factory,
      generatedSkillPackage: {
        entrySkill: skillId,
        internalSkills: [],
        packageRoot: generated.packageRoot,
        enginePath: generated.enginePath,
        evalManifestPath: generated.evalManifestPath,
        controlPlane: generated.controlPlane,
      },
    },
  };
  delete updated.eval;
  delete updated.review;
  delete updated.ready;
  delete updated.conflict;
  await writeBundleAuthoringState(options.projectRoot, updated);
  return updated;
}

export async function initializeBundleFactoryState(options: {
  projectRoot: string;
  name: string;
  filePath: string;
}): Promise<BundleAuthoringState> {
  const projectRoot = path.resolve(options.projectRoot);
  const plan = normalizeBundleFactoryPlan({
    plan: await readBundleFactoryPlan(path.resolve(options.filePath)),
    projectPreferredSkills: await readSkillPreferences(projectRoot),
  });
  const resolvedSkills = await discoverBundleCandidates({
    projectRoot,
    preferences: plan.preferredSkills.length > 0 ? plan.preferredSkills : null,
  });
  const factoryResolvedSkills = resolvedSkills.map((candidate) => ({
    query: candidate.name,
    preferenceIndex: candidate.preferenceIndex,
    status: candidate.status,
    sources: candidate.sources,
  }));
  const planArtifact = await writeBundleFactoryPlanArtifact({
    projectRoot,
    name: options.name,
    plan,
  });
  const flattenedCandidates = resolvedSkills.flatMap((candidate) => candidate.sources);
  const factory: BundleFactoryMetadata = await composeFactoryMetadata({
    goal: plan.goal,
    preferredSkills: plan.preferredSkills,
    compositionEntrySkills: plan.callChain.map((item) => item.skill),
    resolvedSkills: factoryResolvedSkills,
    callChain: plan.callChain,
    deviations: structuredClone(plan.deviations),
    engineMode: plan.engineMode,
    runnerMode: plan.runnerMode,
    planPath: planArtifact.planPath,
    planHash: planArtifact.planHash,
  });

  let state: BundleAuthoringState | null = null;
  try {
    state = await reconcileBundleAuthoringState(projectRoot, options.name);
  } catch (error) {
    if (!isMissingStateError(error)) throw error;
  }

  if (!state) {
    const optimizeSourceRoot =
      plan.mode === 'optimize' ? path.resolve(projectRoot, plan.sourceRoot!) : null;
    state =
      plan.mode === 'optimize'
        ? await optimizeBundleDraft({
            projectRoot,
            name: options.name,
            sourceRoot: optimizeSourceRoot!,
            candidates: flattenedCandidates,
            creator: plan.creator,
            defaultLocale: plan.defaultLocale,
            locales: plan.locales,
            engineEnabled: plan.engineEnabled,
            factory,
          })
        : await createBundleDraft({
            projectRoot,
            name: options.name,
            candidates: flattenedCandidates,
            creator: plan.creator,
            defaultLocale: plan.defaultLocale,
            locales: plan.locales,
            engineEnabled: plan.engineEnabled,
            factory,
          });
    return state;
  }

  if (plan.mode && plan.mode !== state.mode) {
    throw new Error(`Bundle ${state.name} already exists in ${state.mode} mode`);
  }

  const updated: BundleAuthoringState = {
    ...state,
    status: 'draft',
    currentHash: null,
    candidates: flattenedCandidates,
    creator: plan.creator,
    defaultLocale: plan.defaultLocale,
    locales: plan.locales,
    engineEnabled: plan.engineEnabled,
    factory,
  };
  delete updated.eval;
  delete updated.review;
  delete updated.ready;
  delete updated.conflict;
  await writeBundleAuthoringState(projectRoot, updated);
  return updated;
}
